config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :menus
  end
  namespace :admin do
      root 'base#index'
      get 'login', to: 'base#login', as: 'login'
      post 'login', to: 'base#do_login', as: 'do_login'
      get 'logout', to: 'base#logout', as: 'logout'
      
      resources :pages
      resources :comments
      resources :users do
        get :newpass, to:'users#new_password', as:'new_password'
        patch :changepass, to:'users#change_password', as:'change_password' 
      end
      resources :categories
      resources :posts
  end
    
    resources :posts, except: [:edit, :update, :add, :create, :destroy]
    get 'blog', to:'posts#index'
    get ':slug-:id-blog', to:'posts#show', as:'post_show'
    get ':slug-:id', to:"pages#show", as:"page_show"
    
    get "category/:id", to:"posts#category", as:"post_by_category"
    get "kategori/:slug", to:"posts#category", as:"post_by_category_with_slug"
    
    root 'homes#index'
    
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    ''
  end
end

app/models/admin/menu.rb
class Admin::Menu < ApplicationRecord
    
    def durum
        if status==true
            '<span class="dotred">•</span>'
        else
            '<span class="dotgreen">•</span>'
        end
    end
    
    
    
    def hedef 
        if target=='_blank'
            "Yeni Pencereden"
        end
    end
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :post
    before_save :add_slug
    
    
    
    def durum
        if status==true
            "Aktif"
        else
            "Pasif"
        end
    end
    
    def ust_kategori
        if !parent || parent==0
            "Yok"
        else
            kategori = Category.find(parent)
            kategori.title
        end
    end
    
    
    private def add_slug
        self.slug = self.title.parameterize
    end
    
    
    
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
end

app/models/page.rb
class Page < ApplicationRecord
    
    mount_uploader :image, CoverUploader
    before_save :add_slug
    
     def durum
        if status==true
            '<div style="color:green; font-size:25px; line-height:20px;">•</div>'.html_safe
        else
            '<div style="color:red; font-size:25px; line-height:20px;">•</div>'.html_safe
        end
    end
    
    
    
    
    def ust_sayfa
        if parent==0 || !parent
            "Yok"
        else
            parentPage = Page.find(parent)
            parentPage.title
        end
    end
    
    
    
    private def add_slug
        self.slug = self.title.parameterize
    end
    
    def seo_title
        if slug.blank?
            "asw"
        else
            slug
        end
    end
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category
    belongs_to :user
    has_one :comment
    mount_uploader :image, CoverUploader
    before_save :add_slug
    
    
    
    
    def durum
        if status==true
            '<div style="color:green; font-size:25px; line-height:20px;">•</div>'.html_safe
        else
            '<div style="color:red; font-size:25px; line-height:20px;">•</div>'.html_safe
        end
    end
    
    
    def seo_title
        if slug.blank?
            "asw"
        else
            slug
        end
    end
    
    
    private def add_slug
        self.slug = self.title.parameterize
    end
    
end

app/models/user.rb
class User < ApplicationRecord
    has_many :post
    has_many :comment
    
    validates :username, presence:true, length:{minimum:3, maximum:16}, uniqueness:true
    validates :password, presence:true, length:{minimum:6, maximum:30}, :on => [:create, :change_password]
    validates :full_name, presence:true
    validates :email, presence:true, uniqueness:true
    
    
    before_save :md5_password
    
    
    def md5_password
        self.password = Digest::MD5.hexdigest(self.password)
    end
    
    
    def group_name
        $user_groups[status]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def show
        @page = Page.where(status:true, id:params[:id]).take
        if !@page.present?
           # redirect_to root_path
            render :not_page
        end
    end
    
    def not_page
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(status:true).order('id DESC').all
  end
    
  def category
      @category = Category.find_by_slug(params[:slug])
      @posts = Post.where(status:true, category_id:@category.id).order('id DESC').all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

    

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :keywords, :desc, :content, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    $user_groups = { 0=>"Pasif Üye", 1=>"Aktif Üye", 2=>"Editör", 3=>"Yönetici" }

end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/pages/_form.html.erb
<%= form_for([:admin, page], html:{class:"form-horizontal"}) do |f| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Sayfa Adı :", class:"control-label col-sm-2" %>
    <div class="col-sm-10"><%= f.text_field :title, class:"form-control" %></div>
  </div>

  <div class="form-group">
    <%= f.label "Etiketler :", class:"control-label col-sm-2" %>
    <div class="col-sm-10"><%= f.text_field :keywords, class:"form-control" %></div>
  </div>

  <div class="form-group">
    <%= f.label "Açıklama :", class:"control-label col-sm-2" %>
    <div class="col-sm-10"><%= f.text_area :desc, class:"form-control" %></div>
  </div>

  <div class="form-group">
    <%= f.label "Üst Sayfa :", class:"control-label col-sm-2" %>
    <div class="col-sm-10"><%= f.collection_select :parent, Page.all, :id, :title, {include_blank: "Üst sayfa yok"}, {class:"form-control"} %></div>
  </div>
  
  <div class="form-group">
    <%= f.label "Görsel :", class:"control-label col-sm-2" %>
    <div class="col-sm-10"><%= f.file_field :image, class:"form-control" %></div>
  </div>
  
  <div class="form-group">
    <%= f.label "Durum :", class:"control-label col-sm-2" %>
    <div class="col-sm-10">
        <label for="page_status"><%= f.check_box :status %> Bu sayfayı yayımla.</label>
        </div>
  </div>

  <div class="form-group">
    <%= f.label "İçerik :", class:"control-label col-sm-2" %>
    <div class="col-sm-10"><%= f.text_area :content, class:"form-control ckeditor" %></div>
  </div>


  <div class="form-group">
   <label for="" class="col-sm-2"> </label>
      <div class="col-sm-10"><%= f.submit "Kaydet", class:"btn btn-primary" %></div>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<div class="div text-center"><h1>Sayfa Düzenle</h1><hr></div>
<%= render 'form', page: @page %>

app/views/admin/pages/index.html.erb
<h1>Sayfalar</h1>
<div style="padding:10px 0px;">
    <%= link_to 'Sayfa Oluştur', new_admin_page_path, class:"btn btn-primary colorwhite" %>
</div>
<table class="table table-hover table-bordered table-striped">
  <thead>
    <tr>
      <th width="35"></th>
      <th width="10"></th>
      <th>Sayfa</th>
      <th width="180">Üst Sayfa</th>
      <th width="10"></th>
      <th width="10"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= image_tag page.image.url , width:"45", height:"40" if page.image.url %></td>
        <td><%= page.durum %></td>
        <td><%= page.title %><br>
            <small><strong>URL:</strong> <%= page_show_url(page.seo_title, page.id) %></small>
        </td>
        <td><%= page.ust_sayfa %></td>
        <td><%= link_to 'Düzenle', edit_admin_page_path(page) %></td>
        <td><%= link_to 'Sil', [:admin, page], method: :delete, data: { confirm: 'Bu sayfayı silmek istediğinizden emin misiniz?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/pages/new.html.erb
<div class="div text-center"><h1>Sayfa Oluştur</h1><hr></div>
<%= render 'form', page: @page %>

app/views/admin/pages/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @page.keywords %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @page.desc %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @page.parent %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= @page.image %>
</p>

<p>
  <strong>Status:</strong>
  <%= @page.status %>
</p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Firstblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/style.css">
  </head>

  <body>
  <% flash[:alertclass] = 'success' if flash[:alertclass].blank? %>
  <%= "<div class=\"alert alert-#{flash[:alertclass]} alert-dismissible\" role=\"alert\">
    <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>
    <div class=\"container text-center\">#{notice}</div></div>".html_safe if notice %> 
   
   <div class="mainmenu">
    <div class="container">
    <ul class="nav nav-pills">
        <li><%= link_to "Başlangıç", admin_root_path %></li>
        <li><%= link_to "Yazılar", admin_posts_path %></li>
        <li><%= link_to "Kategoriler", admin_categories_path %></li>
        <li><%= link_to "Sayfalar", admin_pages_path %></li>
        <li><%= link_to "Yorumlar", admin_comments_path %></li>
        <li><%= link_to "Üyeler", admin_users_path %></li>
        <li><%= link_to "Üst Menü", admin_menus_path %></li>
        <li><%= link_to "Çıkış Yap", admin_logout_path %></li>
    </ul>
    </div>
    </div>
   
    <div class="container">
    <%= yield %>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="//cdn.ckeditor.com/4.7.3/standard/ckeditor.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="/js/custom.js"></script> 
    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Firstblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Exo+2:400,500,600,700|Roboto+Condensed:400,700&amp;subset=latin-ext" rel="stylesheet">

    <link rel="stylesheet" href="/css/style.css">
  </head>

  <body id="site">
   <div class="container maincontent">
   
   <nav class="main-menu">
    <ul class="nav nav-pills">
    <% Admin::Menu.order('sort').where(status:false).each do |menu| %>
        <li><%= link_to menu.title, menu.url, name:menu.desc, target:menu.target %></li>
    <% end %>
    </ul>        
   </nav>
   
   
   <div class="clearfix"></div>
   
    <div class="row">
    <div class="col-md-9"><%= yield %>
        <div class="clearfix"></div>
    </%></div>
    <div class="col-md-3">
       
        <div class="row p0 search_box">
        <div class="col-xs-12 p0">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Aranacak birşey yazın..">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">Ara!</button>
              </span>
            </div><!-- /input-group -->
          </div><!-- /.col-lg-6 -->
          <div class="cleafix"></div>
        </div><!-- /.row -->
        
        <% categories = Category.where(status:true).all %>
        <% if categories.present? %>
        <div class="panel panel-default">
        <div class="panel-heading">KATEGORİLER</div>
        <div class="panel-body">
        <ul class="nav nav-pills nav-stacked p0 m0">
        <% categories.each do |category| %>
            <li><%= link_to category.title, "/kategori/#{category.slug}" %></li>
        <% end %>
        </ul>
        </div>
        </div>
        <% end %>
        
        <div class="socialicons">
            <%= link_to 'F', 'http://facebook.com', class:'facebook' %>
            <%= link_to 'T', 'http://twitter.com', class:'twitter' %>
            <%= link_to 'Y', 'http://youtube.com', class:'youtube' %>
            <%= link_to 'L', 'http://linkedin.com', class:'linkedin' %>
            <%= link_to 'R', 'http://localhsot', class:'sitemap' %>
        </div>
        
        
        
        <div class="panel panel-default">
            <div class="panel-heading">ÇOK OKUNANLAR</div>
            <div class="panel-body"></div>
        </div>
        
        
        <div><%= image_tag 'https://i.hizliresim.com/QA8GdV.jpg', class:'img-responsive center-block' %></div>
        
        
        
        
    </div>
    </div>
    
    
    <footer class="text-center">
    <p>AtabasSoftware</p>
    </footer>
    
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="//cdn.ckeditor.com/4.7.3/standard/ckeditor.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="/js/custom.js"></script> 
    
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Firstblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/style.css">
  </head>

  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="//cdn.ckeditor.com/4.7.3/standard/ckeditor.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="/js/custom.js"></script> 
    
  </body>
</html>

app/views/pages/not_page.html.erb
<div class="alert alert-danger">Aradığınız sayfa bulunamadı. </div>

app/views/pages/show.html.erb
<article id="single">
    <head class="text-center">
        <h1 class="single_post_title" title="<%= @page.title %>">• <%= @page.title %></h1><hr> 
        <div class="row single_post_icons">
            <div class="col-xs-12 col-sm-4 text-center"><em class="glyphicon glyphicon-calendar"></em> <%= @page.created_at.strftime("%d %m %Y %H:%M") %></div>

        </div>
    </head>
    
    <hr>
    <section class="single_post_content"><%= image_tag @page.image.url, class:'single_post_cover', alt:@page.title  if @page.image.present? %> <%= @page.content.html_safe %></section>
</article>