config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :menus
  end
  namespace :admin do
      root 'base#index'
      get 'login', to: 'base#login', as: 'login'
      post 'login', to: 'base#do_login', as: 'do_login'
      get 'logout', to: 'base#logout', as: 'logout'
      
      resources :pages
      resources :comments
      resources :users do
        get :newpass, to:'users#new_password', as:'new_password'
        patch :changepass, to:'users#change_password', as:'change_password' 
      end
      resources :categories
      resources :posts
  end
    
    resources :posts, except: [:edit, :update, :add, :create, :destroy]
    get 'blog', to:'posts#index'
    get ':slug-:id-blog', to:'posts#show', as:'post_show'
    get ':slug-:id', to:"pages#show", as:"page_show"
    
    get "category/:id", to:"posts#category", as:"post_by_category"
    get "kategori/:slug", to:"posts#category", as:"post_by_category_with_slug"
    
    root 'homes#index'
    
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'login', only: [:login, :do_login]
  layout 'admin', except: [:login, :do_login]
    
  before_action :admin_login_control, except: [:login, :do_login]
  before_action :admin_login_login_control, only: [:login, :do_login]
  def index
  end
    
    
  def login
      
      
  end
    
  def do_login
      data = params.require(:user).permit(:username, :password)
      username = data[:username]
      password = Digest::MD5.hexdigest(data[:password])
      
      user = User.where(username: username, password: password).take
      
      if user
          session[:status] = true
          session[:level] = user.status
          session[:user_id] = user.id
          redirect_to admin_root_path
      else
          redirect_to admin_login_path, notice: 'Bir hata oluştu tekrar deneyin.'
      end
  end
    
  def logout
    if session[:status]==true
        reset_session
    end
      redirect_to admin_root_path
  end
    
    
  def admin_login_control
    if session[:status]!=true || session[:level]!=3
        redirect_to admin_login_path
    end
  end
    
  def admin_login_login_control
      if session[:status]==true && session[:level]==3
        redirect_to admin_root_path
    end
  end
end

app/helpers/base_helper.rb
module BaseHelper
end

app/views/admin/base/index.html.erb
<hr>
<div class="col-md-4">
<div class="panel panel-default">
<div class="panel-heading text-center"><strong>SAYFALAR</strong></div>
<div class="panel-body">
<ul class="list-group m0">
    <li class="list-group-item"><span class="badge"><%= Page.all.size %></span> Tüm Sayfalar</li>
    <li class="list-group-item"><span class="badge"><%= Page.where(status: true).size %></span> Aktif Sayfalar</li>
    <li class="list-group-item"><span class="badge"><%= Page.where(status: false).size %></span> Pasif Sayfalar</li>
    <li class="list-group-item"><%= link_to "Sayfa Listesi", admin_pages_path, class:"btn btn-default center-block " %></li>
    <li class="list-group-item"><%= link_to "Yeni Sayfa Ekle", new_admin_page_path, class:"btn btn-default center-block    " %></li>
</ul>
</div>
</div>
</div>



<div class="col-md-4">
<div class="panel panel-default">
<div class="panel-heading text-center"><strong>YAZILAR</strong></div>
<div class="panel-body">
<ul class="list-group m0">
    <li class="list-group-item"><span class="badge"><%= Post.all.size %></span> Tüm Yazılar</li>
    <li class="list-group-item"><span class="badge"><%= Post.where(status: true).size %></span> Aktif Yazılar</li>
    <li class="list-group-item"><span class="badge"><%= Post.where(status: false).size %></span> Pasif Yazılar</li>
    <li class="list-group-item"><%= link_to "Yazı Listesi", admin_posts_path, class:"btn btn-default center-block " %></li>
    <li class="list-group-item"><%= link_to "Yeni Yazı Ekle", new_admin_post_path, class:"btn btn-default center-block    " %></li>
</ul>
</div>
</div>
</div>



<div class="col-md-4">
<div class="panel panel-default">
<div class="panel-heading text-center"><strong>KATEGORİLER</strong></div>
<div class="panel-body">
<ul class="list-group m0">
    <li class="list-group-item"><span class="badge"><%= Category.all.size %></span> Tüm Kategoriler</li>
    <li class="list-group-item"><span class="badge"><%= Category.where(status: true).size %></span> Aktif Kategoriler</li>
    <li class="list-group-item"><span class="badge"><%= Category.where(status: false).size %></span> Pasif Kategoriler</li>
    <li class="list-group-item"><%= link_to "Kategori Listesi", admin_categories_path, class:"btn btn-default center-block " %></li>
    <li class="list-group-item"><%= link_to "Yeni Kategori Ekle", admin_categories_path, class:"btn btn-default center-block    " %></li>
</ul>
</div>
</div>
</div>




<div class="col-md-4">
<div class="panel panel-default">
<div class="panel-heading text-center"><strong>YORUMLAR</strong></div>
<div class="panel-body">
<ul class="list-group m0">
    <li class="list-group-item"><span class="badge"><%= Comment.all.size %></span> Tüm Yorumlar</li>
    <li class="list-group-item"><span class="badge"><%= Comment.where(status: true).size %></span> Aktif Yorumlar</li>
    <li class="list-group-item"><span class="badge"><%= Comment.where(status: false).size %></span> Pasif Yorumlar</li>
    <li class="list-group-item"><%= link_to "Yorum Listesi", admin_comments_path, class:"btn btn-default center-block " %></li>
    <li class="list-group-item"><%= link_to "Yeni Yorum Ekle", admin_comments_path, class:"btn btn-default center-block    " %></li>
</ul>
</div>
</div>
</div>




<div class="col-md-4">
<div class="panel panel-default">
<div class="panel-heading text-center"><strong>KULLANICILAR</strong></div>
<div class="panel-body">
<ul class="list-group m0">
    <li class="list-group-item"><span class="badge"><%= User.all.size %></span> Tüm Kullanıcılar</li>
    <li class="list-group-item"><span class="badge"><%= User.where(status: [1,2,3]).size %></span> Aktif Kullanıcılar</li>
    <li class="list-group-item"><span class="badge"><%= User.where.not(status: [1,2,3]).size %></span> Pasif Kullanıcılar</li>
    <li class="list-group-item"><%= link_to "Kullanıcı Listesi", admin_users_path, class:"btn btn-default center-block " %></li>
    <li class="list-group-item"><%= link_to "Yeni Kullanıcı Ekle", new_admin_user_path, class:"btn btn-default center-block    " %></li>
</ul>
</div>
</div>
</div>

app/views/admin/base/login.html.erb
<div id="loginForm">
    <h3 class="p0 m0 text-center">GİRİŞ YAP</h3>
    <div class="clearfix"></div>
    <%= "<div class=\"clearfix\"></div><div class=\"alert alert-danger\">#{notice}</div>".html_safe if notice %>
    <%= form_for('user', url:admin_do_login_path, method: :post) do |f| %>
    <div class="form-group">
        <div class="col-xs-12"><label for="" class="control-label">Kullanıcı Adı</label></div>
        <div class="col-xs-12"><%= f.text_field 'username', class:'form-control'%></div>
        <div class="clearfix"></div>
    </div>
    
    <div class="form-group">
        <div class="col-xs-12"><label for="" class="control-label">Şifre</label></div>
        <div class="col-xs-12"><%= f.password_field 'password', class:'form-control'%></div>
        <div class="clearfix"></div>
    </div>
    
    <div class="form-group">
        <div class="col-xs-12"><%= f.submit 'Giriş Yap', class:'btn btn-primary'%></div>
        <div class="clearfix"></div>
    </div>
    
    <% end %>
</div>