config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :menus
  end
  namespace :admin do
      root 'base#index'
      get 'login', to: 'base#login', as: 'login'
      post 'login', to: 'base#do_login', as: 'do_login'
      get 'logout', to: 'base#logout', as: 'logout'
      
      resources :pages
      resources :comments
      resources :users do
        get :newpass, to:'users#new_password', as:'new_password'
        patch :changepass, to:'users#change_password', as:'change_password' 
      end
      resources :categories
      resources :posts
  end
    
    resources :posts, except: [:edit, :update, :add, :create, :destroy]
    get 'blog', to:'posts#index'
    get ':slug-:id-blog', to:'posts#show', as:'post_show'
    get ':slug-:id', to:"pages#show", as:"page_show"
    
    get "category/:id", to:"posts#category", as:"post_by_category"
    get "kategori/:slug", to:"posts#category", as:"post_by_category_with_slug"
    
    root 'homes#index'
    
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :post
    before_save :add_slug
    
    
    
    def durum
        if status==true
            "Aktif"
        else
            "Pasif"
        end
    end
    
    def ust_kategori
        if !parent || parent==0
            "Yok"
        else
            kategori = Category.find(parent)
            kategori.title
        end
    end
    
    
    private def add_slug
        self.slug = self.title.parameterize
    end
    
    
    
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_url, notice: 'Kategori Oluşturuldu.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to edit_admin_category_path(@category), notice: 'Kategori Güncellendi.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Kategori başarılı bir şekilde silindi.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :desc, :parent, :status)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, category], html:{class:'form-horizontal'}) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Kategori Adı :", class:'control-label col-sm-2' %>
    <div class="col-sm-10"><%= f.text_field :title, class:'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label "Açıklama", class:'control-label col-sm-2' %>
      <div class="col-sm-10"><%= f.text_area :desc, class:'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label "Üst Kategori", class:'control-label col-sm-2' %>
      <div class="col-sm-10"><%= f.collection_select :parent, Category.all, :id, :title, {include_blank: "Üst kategori yok"}, {class:'form-control'} %></div>
  </div>

  <div class="form-group">
    <%= f.label "Durum", class:'control-label col-sm-2' %>
      <div class="col-sm-10"><%= f.check_box :status %></div>
  </div>

  <div class="form-group">
        <label for="" class="control-label col-sm-2"> </label>
        <div class="col-sm-10"><%= f.submit "Kaydet", class:"btn btn-primary" %></div>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="div text-center"><h1>Kategori Düzenle</h1><hr></div>
<%= render 'form', category: @category %>

app/views/admin/categories/index.html.erb
<h1>Kategoriler</h1>
<div style="padding:10px 0px;">
    <%= link_to 'Kategori Oluştur', new_admin_category_path, class:"btn btn-primary colorwhite" %>
</div>
<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th>Kategori</th>
      <th>Açıklama</th>
      <th>Üst</th>
      <th>Durum</th>
      <th width="10"></th>
      <th width="10"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.desc %></td>
        <td><%= category.ust_kategori %></td>
        <td><%= category.durum %></td>
        <td><%= link_to 'Düzenle', edit_admin_category_path(category) %></td>
        <td><%= link_to 'Sil', admin_category_url(category), method: :delete, data: { confirm: 'Bu kategoriyi silmek istediğinizden emin misiniz?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/categories/new.html.erb
<div class="div text-center"><h1>Yeni Kategori Oluştur</h1><hr></div>
<%= render 'form', category: @category %>

app/views/admin/categories/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @category.desc %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @category.parent %>
</p>

<p>
  <strong>Status:</strong>
  <%= @category.status %>
</p>

<%= link_to 'Edit', edit_admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>