config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :menus
  end
  namespace :admin do
      root 'base#index'
      get 'login', to: 'base#login', as: 'login'
      post 'login', to: 'base#do_login', as: 'do_login'
      get 'logout', to: 'base#logout', as: 'logout'
      
      resources :pages
      resources :comments
      resources :users do
        get :newpass, to:'users#new_password', as:'new_password'
        patch :changepass, to:'users#change_password', as:'change_password' 
      end
      resources :categories
      resources :posts
  end
    
    resources :posts, except: [:edit, :update, :add, :create, :destroy]
    get 'blog', to:'posts#index'
    get ':slug-:id-blog', to:'posts#show', as:'post_show'
    get ':slug-:id', to:"pages#show", as:"page_show"
    
    get "category/:id", to:"posts#category", as:"post_by_category"
    get "kategori/:slug", to:"posts#category", as:"post_by_category_with_slug"
    
    root 'homes#index'
    
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :post
    has_many :comment
    
    validates :username, presence:true, length:{minimum:3, maximum:16}, uniqueness:true
    validates :password, presence:true, length:{minimum:6, maximum:30}, :on => [:create, :change_password]
    validates :full_name, presence:true
    validates :email, presence:true, uniqueness:true
    
    
    before_save :md5_password
    
    
    def md5_password
        self.password = Digest::MD5.hexdigest(self.password)
    end
    
    
    def group_name
        $user_groups[status]
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_user_custom, only: [:new_password, :change_password]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @show_items = true
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to edit_admin_user_url(@user), notice: 'Kullanıcı Oluşturuldu.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to edit_admin_user_url(@user), notice: 'Kullanıcı Bilgileri Güncellendi.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'Kullanıcı Sistemden Silindi.' }
      format.json { head :no_content }
    end
  end
    
    
    
  def new_password
  end
    
  def change_password
      @post_password_data = params.require(:user).permit(:password, :repassword)
      password = @post_password_data[:password]
      repassword = @post_password_data[:repassword]
      
      if password.size<6
          flash[:alertclass] = "danger"
          redirect_to admin_user_new_password_path(params[:user_id]), notice: "Parolanız en az 6 karakterden oluşmalıdır lütfen tekrar deneyin."
      elsif !password.eql?(repassword)
          flash[:alertclass] = "danger"
          redirect_to admin_user_new_password_path(params[:user_id]), notice: "Parolalar eşit değil. Yeniden deneyin."
      else
          if @user.update(user_params)
            redirect_to admin_user_new_password_path(params[:user_id]), notice: "Parola Değiştirildi."
          else
            flash[:alertclass] = "danger"
            redirect_to admin_user_new_password_path(params[:user_id]), notice: "Bir sorun oluştu ve parola değişmedi."
          end
          
      end
  end
    
    
    
    
    

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    def set_user_custom
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :full_name, :email, :gender, :birthday, :status)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, user],  data:{abide:''}, html:{class:"form-horizontal" }) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    

  <div class="form-group">
    <%= f.label "Kullanıcı Adı :", class:"control-label col-sm-2" %>
    <div class="col-sm-10">
        <% if @show_items.present? %>
            <%= f.text_field :username, class:"form-control" %>
        <% else %>
            <%= f.text_field :username, class:"form-control", disabled:'' %>
        <% end %>
    </div>
  </div>

  <% if @show_items.present? %>
  <div class="form-group">
    <%= f.label "Parola :", class:"control-label col-sm-2" %>
    <div class="col-sm-10"><%= f.text_field :password, class:"form-control" %></div>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label "E-posta :", class:"control-label col-sm-2" %>
    <div class="col-sm-10"><%= f.text_field :email, class:"form-control" %></div>
  </div>
  
  <div class="form-group">
    <%= f.label "Ad ve Soyad :", class:"control-label col-sm-2" %>
    <div class="col-sm-10"><%= f.text_field :full_name, class:"form-control" %></div>
  </div>

  <div class="form-group">
    <%= f.label "Cinsiyet :", class:"control-label col-sm-2" %>
    <div class="col-sm-10"><%= f.select :gender, ["Erkek","Kadın"],{}, {class:"form-control"} %></div>
  </div>

  <div class="form-group">
    <%= f.label "Doğum Tarihi :", class:"control-label col-sm-2" %>
    <div class="col-sm-10"><%= f.text_field :birthday, class:"form-control", placeholder:"Gün-Ay-Yıl olarak giriniz Ör:13-06-1991" %></div>
  </div>

  <div class="form-group">
    
    <%= f.label "Durum :", class:"control-label col-sm-2" %>
    <div class="col-sm-10"><%= f.select :status, $user_groups.collect{ |k,v| [v, k] }, {}, {class:"form-control"} %></div>
  </div>

  <div class="form-group">
   <label for="" class="control-label col-sm-2"> </label>
    <div class="col-sm-10"><%= f.submit "Kaydet", class:"btn btn-primary" %></div>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="text-center"><h1>Kullanıcı Bilgilerini Düzenle</h1><hr></div>
<%= render 'form', user: @user %>

app/views/admin/users/index.html.erb
<h1>Kullanıcılar</h1>
<div style="padding:10px 0px;"><%= link_to 'Yeni Kullanıcı', new_admin_user_path, class:"btn btn-primary colorwhite" %></div>
<table class="table table-bordered table-hover table-striped">
  <thead>
    <tr>
      <th>Kullanıcı</th>
      <th>Kullanıcı Adı</th>
      <th>E-posta</th>
      <th width="100">Cinsiyet</th>
      <th width="130">Doğrum Tarihi</th>
      <th width="100">Durum</th>
      <th width="100"></th>
      <th width="10"></th>
      <th width="10"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.gender %></td>
        <td><%= user.birthday %></td>
        <td><%= user.group_name %></td>
        <td><%= link_to 'Şifre Değiş', admin_user_new_password_path(user) %></td>
        <td><%= link_to 'Düzenle', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Sil', [:admin, user], method: :delete, data: { confirm: 'Üyeyi silmek istediğinizden emin misiniz?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/users/new.html.erb
<div class="text-center"><h1>Yeni Kullanıcı Oluştur</h1><hr></div>
<%= render 'form', user: @user %>

app/views/admin/users/new_password.html.erb
<div class="text-center"><h1>Kullanıcının Parolasını Güncelle</h1><hr></div>
   <%= form_for(@user,  url: admin_user_change_password_path(@user.id), method: :patch, html:{class:"form-horizontal" }) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

  <div class="form-group">
    <%= f.label "Kullanıcı Adı :", class:"control-label col-sm-2" %>
    <div class="col-sm-10">
        <% if @show_items.present? %>
            <%= f.text_field :username, class:"form-control" %>
        <% else %>
            <%= f.text_field :username, class:"form-control", disabled:'' %>
        <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "Parola :", class:"control-label col-sm-2" %>
    <div class="col-sm-10"><%= f.password_field :password, class:"form-control" %></div>
  </div>
  
  <div class="form-group">
    <%= f.label "Parola Tekrar :", class:"control-label col-sm-2" %>
    <div class="col-sm-10"><%= f.password_field 'repassword', class:"form-control" %></div>
  </div>

  <div class="form-group">
   <label for="" class="control-label col-sm-2"> </label>
    <div class="col-sm-10"><%= f.submit "Kaydet", class:"btn btn-primary" %></div>
  </div>
<% end %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @user.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user.status %>
</p>